//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace СкладОИТ.XPO.СкладОИТ
{

    [DeferredDeletion(false)]
    [Persistent(@"Склад.Номенклатура")]
    public partial class Номенклатура : XPObject
    {
        string fНаименование;
        [Size(SizeAttribute.Unlimited)]
        public string Наименование
        {
            get { return fНаименование; }
            set { SetPropertyValue<string>(nameof(Наименование), ref fНаименование, value); }
        }
        string fСерияномер;
        [Size(255)]
        [Persistent(@"Серия номер")]
        public string Серияномер
        {
            get { return fСерияномер; }
            set { SetPropertyValue<string>(nameof(Серияномер), ref fСерияномер, value); }
        }
        [Association(@"ВыданнаяНоменклатура-Номенклатура")]
        public XPCollection<ВыданнаяНоменклатура> ВыданнаяНоменклатура { get { return GetCollection<ВыданнаяНоменклатура>(nameof(ВыданнаяНоменклатура)); } }
        [Association(@"ВыданнаяНоменклатура_ПродажаООО-Номенклатура")]
        public XPCollection<ВыданнаяНоменклатура_ПродажаООО> ВыданнаяНоменклатура_ПродажаООО { get { return GetCollection<ВыданнаяНоменклатура_ПродажаООО>(nameof(ВыданнаяНоменклатура_ПродажаООО)); } }
    }

}
