//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace СкладОИТ.XPO.СкладОИТ
{

    [DeferredDeletion(false)]
    [Persistent(@"Склад.Отдел")]
    public partial class Отдел : XPObject
    {
        string fНазвание;
        public string Название
        {
            get { return fНазвание; }
            set { SetPropertyValue<string>(nameof(Название), ref fНазвание, value); }
        }
        [Association(@"ВыданнаяНоменклатура-Отдел")]
        public XPCollection<ВыданнаяНоменклатура> ВыданнаяНоменклатура { get { return GetCollection<ВыданнаяНоменклатура>(nameof(ВыданнаяНоменклатура)); } }
        [Association(@"ВыданнаяНоменклатура_ПродажаООО-Отдел")]
        public XPCollection<ВыданнаяНоменклатура_ПродажаООО> ВыданнаяНоменклатура_ПродажаООО { get { return GetCollection<ВыданнаяНоменклатура_ПродажаООО>(nameof(ВыданнаяНоменклатура_ПродажаООО)); } }
    }

}
