//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace СкладОИТ.XPO.СкладОИТ
{

    [DeferredDeletion(false)]
    [Persistent(@"Склад.ПрограммноеОбеспечение")]
    public partial class ПрограммноеОбеспечение : XPObject
    {
        string fНаименование;
        public string Наименование
        {
            get { return fНаименование; }
            set { SetPropertyValue<string>(nameof(Наименование), ref fНаименование, value); }
        }
        [Association(@"СрокЛицензииПО-ПрограммноеОбеспечение")]
        public XPCollection<СрокЛицензииПО> СрокЛицензииПО { get { return GetCollection<СрокЛицензииПО>(nameof(СрокЛицензииПО)); } }
    }

}
