//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace СкладОИТ.XPO.СкладОИТ
{

    [DeferredDeletion(false)]
    [Persistent(@"Склад.СрокЛицензииПО")]
    public partial class СрокЛицензииПО : XPObject
    {
        ПрограммноеОбеспечение fПрограммноеОбеспечениеID;
        [Association(@"СрокЛицензииПО-ПрограммноеОбеспечение")]
        public ПрограммноеОбеспечение ПрограммноеОбеспечениеID
        {
            get { return fПрограммноеОбеспечениеID; }
            set { SetPropertyValue<ПрограммноеОбеспечение>(nameof(ПрограммноеОбеспечениеID), ref fПрограммноеОбеспечениеID, value); }
        }
        DateTime fДатаПриобретения;
        public DateTime ДатаПриобретения
        {
            get { return fДатаПриобретения; }
            set { SetPropertyValue<DateTime>(nameof(ДатаПриобретения), ref fДатаПриобретения, value); }
        }
        DateTime fСрокЛицензии;
        public DateTime СрокЛицензии
        {
            get { return fСрокЛицензии; }
            set { SetPropertyValue<DateTime>(nameof(СрокЛицензии), ref fСрокЛицензии, value); }
        }
    }

}
